#!/usr/bin/env python3
"""A.0.2.diag #2 — Forward-return analysis with t-stat and autocorrelation.

For each entry signal generated by simulate_strategy (cost-off, gross only),
ignore the strategy's own SL/TP and compute the price's forward return at
horizons h ∈ {1, 5, 15, 50} 1H bars from entry. Tests whether the signal
itself carries predictive information independently of execution.

Output per symbol × horizon:
  - mean_forward_return_pct
  - stdev_forward_return_pct
  - t_statistic = mean / (stdev / sqrt(n))
  - autocorrelation_lag1 (Pearson, on the per-trade fwd-return series)
  - n_observations (entries with at least h bars of forward data available)

t-stat tier (per spec #281):
  t < 1.5  → noise  (strategy has no predictive edge)
  1.5 ≤ t < 2.5 → marginal  (won't survive Deflated Sharpe)
  t ≥ 2.5  → solid  (info exists; problem is execution / sizing / costs)

Run:
    python scripts/a02_diag_2_forward_return.py --out /tmp/a02_diag_2.json
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

import sys
_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from scripts._a02_diag_lib import (
    CURATED_SYMBOLS, fetch_data, load_config, run_simulation,
)


HORIZONS = (1, 5, 15, 50)


def _forward_returns_for_entries(
    entries: list[tuple[pd.Timestamp, str]],
    close_1h: pd.Series,
    horizon: int,
) -> np.ndarray:
    """For each (entry_time, direction), compute fwd return at +horizon 1H bars.

    LONG fwd_return = (close[t+h] - close[t]) / close[t]
    SHORT fwd_return = -(close[t+h] - close[t]) / close[t]
                     = (close[t] - close[t+h]) / close[t]

    Drops entries that don't have h bars of forward data.
    """
    rets: list[float] = []
    idx = close_1h.index
    for entry_time, direction in entries:
        # Locate the bar at or just before entry_time (entries align to 1H bar
        # opens by simulate_strategy contract, so == should usually hit; use
        # ffill-like behavior to be robust to off-by-one).
        try:
            i = idx.get_indexer([entry_time], method="ffill")[0]
        except Exception:
            continue
        if i < 0 or i + horizon >= len(close_1h):
            continue
        p_t = float(close_1h.iloc[i])
        p_th = float(close_1h.iloc[i + horizon])
        if p_t <= 0:
            continue
        ret = (p_th - p_t) / p_t
        if direction == "SHORT":
            ret = -ret
        rets.append(ret)
    return np.asarray(rets, dtype=float)


def _t_statistic(returns: np.ndarray) -> float:
    n = len(returns)
    if n < 2:
        return float("nan")
    sd = float(np.std(returns, ddof=1))
    if sd == 0 or not math.isfinite(sd):
        return float("nan")
    return float(np.mean(returns)) / (sd / math.sqrt(n))


def _autocorr_lag1(returns: np.ndarray) -> float:
    """Pearson autocorrelation between r[i] and r[i+1]. Treats trade entries
    as the time index (entries are time-ordered in simulate_strategy)."""
    if len(returns) < 3:
        return float("nan")
    a = returns[:-1]
    b = returns[1:]
    if np.std(a, ddof=1) == 0 or np.std(b, ddof=1) == 0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def analyze_symbol(symbol: str, cfg: dict, overrides: dict) -> dict:
    df1h, *_ = fetch_data(symbol)
    if df1h.empty:
        return {"symbol": symbol, "error": "no data"}

    trades, _equity = run_simulation(
        symbol, with_costs=False, cfg=cfg, overrides=overrides,
    )
    if not trades:
        return {"symbol": symbol, "error": "no trades", "n_entries": 0}

    entries = [
        (pd.Timestamp(t["entry_time"]).tz_localize(None)
         if pd.Timestamp(t["entry_time"]).tzinfo
         else pd.Timestamp(t["entry_time"]),
         t["direction"])
        for t in trades
    ]
    close_1h = df1h["close"]
    if close_1h.index.tz is not None:
        close_1h = close_1h.tz_localize(None)

    out = {"symbol": symbol, "n_entries_total": len(entries), "horizons": {}}
    for h in HORIZONS:
        rets = _forward_returns_for_entries(entries, close_1h, h)
        n = len(rets)
        if n == 0:
            out["horizons"][h] = {"n_observations": 0, "error": "no fwd data"}
            continue
        out["horizons"][h] = {
            "n_observations": n,
            "mean_pct": float(np.mean(rets)) * 100.0,
            "stdev_pct": float(np.std(rets, ddof=1)) * 100.0 if n > 1 else float("nan"),
            "t_statistic": _t_statistic(rets),
            "autocorrelation_lag1": _autocorr_lag1(rets),
        }
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="/tmp/a02_diag_2.json")
    ap.add_argument("--symbols", default=",".join(CURATED_SYMBOLS))
    args = ap.parse_args()

    cfg, overrides = load_config()
    symbols = [s.strip() for s in args.symbols.split(",") if s.strip()]

    results = []
    for sym in symbols:
        print(f"  → {sym}", flush=True)
        results.append(analyze_symbol(sym, cfg, overrides))

    Path(args.out).write_text(json.dumps(results, indent=2, default=str))
    print(f"\nWrote {args.out}")

    # Summary table
    print("\n## Forward-return analysis (gross, no SL/TP, hold for h bars)")
    for h in HORIZONS:
        print(f"\n### h = +{h} 1H bars")
        print("| Symbol | n_obs | mean_pct | t_stat | autocorr_lag1 | tier |")
        print("|---|---:|---:|---:|---:|---|")
        for r in results:
            sym = r["symbol"]
            if "horizons" not in r or h not in r["horizons"]:
                print(f"| {sym} | — | — | — | — | (no data) |")
                continue
            d = r["horizons"][h]
            if d.get("n_observations", 0) == 0:
                print(f"| {sym} | 0 | — | — | — | (no fwd data) |")
                continue
            t = d["t_statistic"]
            tier = "noise" if abs(t) < 1.5 else (
                "marginal" if abs(t) < 2.5 else "solid"
            )
            print(
                f"| {sym} | {d['n_observations']} | "
                f"{d['mean_pct']:+.4f} | {t:+.2f} | "
                f"{d['autocorrelation_lag1']:+.3f} | {tier} |"
            )


if __name__ == "__main__":
    main()
